<?php
namespace ierusalim\BaseConvert;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-16 at 11:24:17.
 */
class Base85VCTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Base85VC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base85VC();
    }

    public function testConstruct()
    {
        $bc = new Base85VC();

        $base85vc = $bc->bco->bases[85];

        $len = strlen($base85vc);
        $this->assertEquals(85, $len);
    }

    /**
     * @covers ierusalim\BaseConvert\Base85VC::base85vc_decode
     * @todo   Implement testBase85vc_decode().
     */
    public function testBase85vc_decode()
    {
        $bco = $this->object;

        $res = $bco->base85vc_decode('');
        $this->assertEquals('', $res);

        $str = "This is a test string";

        $res = $bco->base85vc_encode($str);

        $dec = $bco->base85vc_decode($res);

        $this->assertEquals($str, $dec);
    }

    /**
     * @covers ierusalim\BaseConvert\Base85VC::base85vc_encode
     * @todo   Implement testBase85vc_encode().
     */
    public function testBase85vc_encode()
    {
        $bco = $this->object;
        $str = '';
        for($i=0; $i<64; $i++) {
            $res = $bco->base85vc_encode($str);
            //var_dump(mb_convert_encoding($res,'cp1251'),'utf-8');
            $dec = $bco->base85vc_decode($res);
            $this->assertEquals($str, $dec);
            $str .= chr(rand(0,255));
        }
    }
}
