<?php
namespace ierusalim\BaseConvert;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-15 at 17:19:37.
 */
class Base6400Test extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Base6400
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base6400;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ierusalim\BaseConvert\Base6400::base6400_decode
     * @todo   Implement testBase6400_decode().
     */
    public function testBase6400_decode()
    {
        $ob = $this->object;
        $src = 'Man is distinguished, not only by his reason, but by this singular passion from other animals, which is a lust of the mind, that by a perseverance of delight in the continued and indefatigable generation of knowledge, exceeds the short vehemence of any carnal pleasure.';

        $str = $ob->base6400_encode($src);
        $dec = $ob->base6400_decode($str);

        $this->assertEquals($src, $dec);
    }

    /**
     * @covers ierusalim\BaseConvert\Base6400::base6400_encode
     * @todo   Implement testBase6400_encode().
     */
    public function testBase6400_encode()
    {
        $ob = $this->object;

        $src = '';
        for($i=0;$i<64;$i++) {
            $str = $ob->base6400_encode($src);
            $dec = $ob->base6400_decode($str);

            $this->assertEquals($src, $dec);
            $src .= chr(rand(0,255));
        }
    }

    /**
     * @covers ierusalim\BaseConvert\Base6400::explodeToUnicode
     * @todo   Implement testExplodeToUnicode().
     */
    public function testExplodeToUnicode()
    {
        $ob = $this->object;
        $string = '䶰䶱䶲䶳䶴䶵䶶䶷䶸䶺䶻䶼䶽䶾䶿 привет 一丁丂七丄';
        $uni_arr = $ob->explodeToUnicode($string);

        $len = mb_strlen($string, 'utf-8');
        $this->assertEquals($len, count($uni_arr));
    }

    /**
     * @covers ierusalim\BaseConvert\Base6400::implodeUnicode
     * @todo   Implement testImplodeUnicode().
     */
    public function testImplodeUnicode()
    {
        $ob = $this->object;
        $string = '䶰䶱䶲䶳䶴䶵䶶䶷䶸䶺䶻䶼䶽䶾䶿 привет 一丁丂七丄';
        $uni_arr = $ob->explodeToUnicode($string);
        $back_str = $ob->implodeUnicode($uni_arr);

        $this->assertEquals($string, $back_str);
    }
}
